# Generated by Django 3.2.6 on 2021-08-17 03:52

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_alter_contactpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactpage',
            name='content',
            field=wagtail.core.fields.StreamField([], blank=True, null=True),
        ),
    ]
