# Generated by Django 3.2.6 on 2021-08-17 03:52

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parallax', '0003_alter_parallaxpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parallaxpage',
            name='content',
            field=wagtail.core.fields.StreamField([], blank=True, null=True),
        ),
    ]
