# Generated by Django 3.2.6 on 2021-08-17 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0004_auto_20210806_1135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePage',
        ),
    ]
